title: OrgCheck
email: vfinet@salesforce.com
description: Org Check is an easy-to-install and easy-to-use Salesforce application in order to quickly analyze your org and its technical debt.
twitter_username: VinceFINET
github_username:  VinceFINET
theme: jekyll-theme-minimal
logo: assets/pngs/Logo+Mascot-v3.png

page_home_label: Home
page_home_url: /
page_preview_label: Preview
page_preview_url: /preview
page_installation_label: Install
page_installation_url: /installation
page_vision_label: Vision
page_vision_url: /vision
page_legal_label: Legal Terms
page_legal_url: /legal
page_tech_datastores_label: Data Stores in OrgCheck
page_tech_datastores_url: /technical/datastores
page_tech_ds_apexclasses_label: Apex Classes
page_tech_ds_apexclasses_url: /technical/datastores/apexclasses
page_tech_ds_flows_label: Flows
page_tech_ds_flows_url: /technical/datastores/flows
page_tech_ds_packages_label: Packages
page_tech_ds_packages_url: /technical/datastores/packages
page_tech_ds_workflowrules_label: Workflow Rules
page_tech_ds_workflowrules_url: /technical/datastores/workflowrules
